### PR TITLE
dumps: dtx_update_abort, key_tree_prepare

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/janekmi/daos/18)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/janekmi/daos/18)* status: all files reviewed, 18 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/janekmi/daos/18#-Nh2A42jDuqk5dUoevwz:-Nh2A42jDuqk5dUoevx-:b-ggcmdt) (no related file):*
Mixing tabs and spaces may cause problems in this case. Can you please replace tabs with spaces?

___
___
*[`dumps/dtx_update_abort.c` line 370 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh1wGWIBgSGmTFFvTX-:-Nh1wGWIBgSGmTFFvTX0:undefined) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L370)):*
> ```C
> 			 * daos_handle_t ak_toh
> 			 * struct vos_io_context *ioc
> 			 */
> ```





_Suggestion:_
```C
			struct vos_object	*obj = ioc->ic_obj;
			struct vos_krec_df	*krec;
			daos_handle_t ak_toh;
			/*
			 * daos_handle_t obj_toh; dkey tree open handle of the object (volatile)
			 * VOS_BTR_DKEY - distribution key tree
			 * SUBTR_CREATE	< may create the subtree
			 * DAOS_INTENT_UPDATE - write/insert
			 */
```
___
*[`dumps/dtx_update_abort.c` line 371 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh29Ikp-q8N8xhqjMx6:-Nh29Ikp-q8N8xhqjMx7:undefined) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L371)):*
> ```C
> 			 * struct vos_io_context *ioc
> 			 */
>                         rc = key_tree_prepare(obj, obj->obj_toh, VOS_BTR_DKEY, dkey, SUBTR_CREATE, DAOS_INTENT_UPDATE, &krec, &ak_toh, ioc->ic_ts_set);
> ```





_Suggestion:_
```C
rc = key_tree_prepare(obj, toh = obj->obj_toh, tclass = VOS_BTR_DKEY, key = dkey, flags = SUBTR_CREATE, intent = DAOS_INTENT_UPDATE, &krec, sub_toh = &ak_toh, ts_set = ioc->ic_ts_set);
```
___
*[`dumps/dtx_update_abort.c` line 371 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh29RGl3Mg_mnQu5tYj:-Nh29C627z4pslBL-O4w:undefined) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L371)):*
> ```C
> 			 * struct vos_io_context *ioc
> 			 */
>                         rc = key_tree_prepare(obj, obj->obj_toh, VOS_BTR_DKEY, dkey, SUBTR_CREATE, DAOS_INTENT_UPDATE, &krec, &ak_toh, ioc->ic_ts_set);
> ```





_Suggestion:_
```C
rc = key_tree_prepare(obj, toh = obj->obj_toh, tclass = VOS_BTR_DKEY, key = dkey, flags = SUBTR_CREATE, intent = DAOS_INTENT_UPDATE, &krec, sub_toh = &ak_toh, ts_set = ioc->ic_ts_set);
struct vos_rec_bundle rbund;
d_iov_t riov;
created = false;
```
___
*[`dumps/dtx_update_abort.c` line 391 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh29dhK83HlQ5Q5llr3:-Nh29dhLEYJMGOItlHdL:undefined) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L391)):*
> ```C
> 				*   there.
> 				*/
>                                 rc = dbtree_fetch(toh, BTR_PROBE_EQ, intent, key, NULL, &riov);
> ```





_Suggestion:_
```C
/* Search the provided \a key and fetch its value (and key if the matched key
* is different with the input key). This function can support advanced range
* search operation based on \a opc.
*/
rc = dbtree_fetch(toh, BTR_PROBE_EQ, intent, key, NULL, &riov);
```
___
*[`dumps/dtx_update_abort.c` line 407 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh29nYT7ZLMK09sQv6y:-Nh29nYT7ZLMK09sQv6z:b-gcxkrh) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L407)):*
> ```C
> 					 */
>                                         btr_rec_fetch(tcx, rec, key_out, val_out);
>                                                 ktr_rec_fetch /* btr_ops(tcx)->to_rec_fetch(&tcx->tc_tins, rec, key, val); */
> ```

I think we can omit this piece.
___
*[`dumps/dtx_update_abort.c` line 410 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh29zR59Ln2hWF6zz-d:-Nh29zR59Ln2hWF6zz-e:undefined) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L410)):*
> ```C
>                                 /* rc == 0 */
> 				krec = rbund.rb_krec;
> 				ilog = &krec->kr_ilog;
> ```





_Suggestion:_
```C
                /* struct vos_krec_df *rb_krec; Returned durable address of the btree record */
				krec = rbund.rb_krec;
                /* struct ilog_df kr_ilog; Incarnation log for key */
				ilog = &krec->kr_ilog;
```
___
*[`dumps/dtx_update_abort.c` line 415 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2AKpv9FGZ_2SfJblE:-Nh2AKpv9FGZ_2SfJblF:b45h) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L415)):*
> ```C
>                                 vos_ilog_ts_ignore(vos_obj2umm(obj), &krec->kr_ilog);
>                                         /* !DAOS_ON_VALGRIND */
>                                 tmprc = vos_ilog_ts_add(ts_set, ilog, key->iov_buf, (int)key->iov_len);
> ```





_Suggestion:_
```C
                                /* Check if the timestamps associated with the ilog are in cache.  If so, add them to the set. */
                                /* void *iov_buf; buffer address */
                                /* size_t iov_len; data length */
                                tmprc = vos_ilog_ts_add(ts_set, ilog, record = key->iov_buf, rec_size = (int)key->iov_len);
```
___
*[`dumps/dtx_update_abort.c` line 418 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2ARnBB19ZZhZ9Aq7C:-Nh2ARnBB19ZZhZ9Aq7D:undefined) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L418)):*
> ```C
>                                         /* vos_ts_in_tx(ts_set) == true */
>                                         /* ilog != NULL */
>                                         idx = ilog_ts_idx_get(ilog);
> ```





_Suggestion:_
```C
                                        idx = ilog_ts_idx_get(root = ilog);
                                                return &root->lr_ts_idx;
```
___
*[`dumps/dtx_update_abort.c` line 420 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2AWymDh0bT2FIrynq:-Nh2AWymDh0bT2FIrynr:undefined) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L420)):*
> ```C
>                                         idx = ilog_ts_idx_get(ilog);
>                                         vos_ts_set_add(ts_set, idx, record, rec_size);
>                                         	hash = vos_hash_get(rec, rec_size, false);
> ```





_Suggestion:_
```C
hash = vos_hash_get(buf = rec, len = rec_size, false);
```
___
*[`dumps/dtx_update_abort.c` line 433 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2Ac4HE_SVMoTRMISo:-Nh2Ac4HE_SVMoTRMISp:undefined) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L433)):*
> ```C
> 						 *		allocated or we detected a duplicate akey.
> 						*/
> 						entry = vos_ts_alloc(ts_set, idx, hash);
> ```





_Suggestion:_
```C
						/* Allocate a new entry in the set. */
						entry = vos_ts_alloc(ts_set, idx, hash);
```
___
*[`dumps/dtx_update_abort.c` line 440 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2AmOy36Cwaap6xrtz:-Nh2AmOy36Cwaap6xru-:b11fw9t) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L440)):*
> ```C
> 							vos_ts_evict_lru(ts_table, &new_entry, idx, hash_idx, info->ti_type);
> 							/** No need to save allocation hash for non-negative entry */
> 							ts_set->ts_entries[ts_set->ts_init_count++] = set_entry;
> ```

Sorry for mixing tabs and spaces. I assumed it would be easier to follow this way.



_Suggestion:_
```C
							struct vos_ts_set_entry	 set_entry = {0};
							struct vos_ts_entry *new_entry;
							ts_table = vos_ts_table_get(false);
							        /* struct vos_ts_table *vtl_ts_table; Timestamp table for xstream */
							        return vos_tls_get(standalone)->vtl_ts_table;
							/* Use the parent entry to get the type info and hash offset for the current object/key. */
							vos_ts_set_get_info(ts_table, ts_set, &info, &hash_offset);
							/** By combining the parent entry offset, we avoid using the same
							 *  index for every key with the same value.
							 */
							hash_idx = vos_ts_get_hash_idx(info, hash, hash_offset);
							/* Internal function to evict LRU and initialize an entry */
							/* uint32_t ti_type; Type identifier */
							vos_ts_evict_lru(ts_table, &new_entry, idx, hash_idx, info->ti_type);
							/* struct vos_ts_entry *se_entry; Pointer to the entry at this level */
							set_entry.se_entry = new_entry;
							/** No need to save allocation hash for non-negative entry */
							/* struct vos_ts_set_entry ts_entries[0]; timestamp entries */
							/* uint32_t ts_init_count; Number of initialized entries */
							ts_set->ts_entries[ts_set->ts_init_count++] = set_entry;
```
___
*[`dumps/dtx_update_abort.c` line 442 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2BBTn-1DPC8vQ7Rat:-Nh2BBTo0fM-MjpL6AlX:b-b7d270) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L442)):*
> ```C
> 							ts_set->ts_entries[ts_set->ts_init_count++] = set_entry;
>                                 /* tmprc == 0 */
>                                 /* sub_toh != NULL */
> ```

I would like to know the value of the `created` variable at this point. Can you please verify and add an appropriate line?



_Suggestion:_
```C
/* sub_toh != NULL */
/* created == false */
```
___
*[`dumps/dtx_update_abort.c` line 443 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2BW7J9dwEA4vHfaX_:-Nh2BW7J9dwEA4vHfaXa:be8l6fh) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L443)):*
> ```C
>                                 /* tmprc == 0 */
>                                 /* sub_toh != NULL */
>                                 rc = tree_open_create(obj, tclass, flags, krec, created, sub_toh);
> ```

Missing definitions.



_Code snippet:_
```C
                                        struct umem_attr *uma = vos_obj2uma(obj);
                                        struct vos_pool *pool = vos_obj2pool(obj);
                                        /* struct vos_container *obj_cont; backref to container */
                                        daos_handle_t coh = vos_cont2hdl(obj->obj_cont);
                                        struct evt_desc_cbs cbs; /* Callbacks and parameters for evtree descriptor */
```
___
*[`dumps/dtx_update_abort.c` line 455 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2BhUi0E4HtfvunVyn:-Nh2BhUi0E4HtfvunVyo:undefined) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L455)):*
> ```C
> 					 * \param toh		[OUT]	Returned tree open handle.
> 					 */
>                                         dbtree_open_inplace_ex(&krec->kr_btr, uma, coh, pool, sub_toh);
> ```





_Suggestion:_
```C
					/* Open a btree from the root address. */
					/* struct btr_root kr_btr; btree root under the key */
					dbtree_open_inplace_ex(root = &krec->kr_btr, uma, coh, priv = pool, sub_toh);
```
___
*[`dumps/dtx_update_abort.c` line 469 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2BxuO5bElUskfFdZS:-Nh2BxuO5bElUskfFdZT:undefined) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L469)):*
> ```C
> 						* \param tcxp		Returned context.
> 						*/
>                                                 rc = btr_context_create(BTR_ROOT_NULL, root, -1, -1, -1, uma, coh, priv, &tcx);
> ```





_Suggestion:_
```C
						struct btr_context *tcx;
						/* Create a btree context (in volatile memory). */
						/* XXX The comment above is misleading. Note use of PMDK below. */
                                                rc = btr_context_create(root_off = BTR_ROOT_NULL, root, tree_class = -1, tree_feats = -1, tree_order = -1, uma, coh, priv, &tcx);
```
___
*[`dumps/dtx_update_abort.c` line 480 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2SwtQBePIch_a1XjP:-Nh2SwtQBePIch_a1XjQ:undefined) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L480)):*
> ```C
> 								 * \param umm [OUT]	The instantiated memory class.
> 								 */
> 								rc = umem_class_init(uma, &tins->ti_umm);
> ```





_Suggestion:_
```C
								 /* Instantiate a memory class \a umm by attributes in \a uma */
								rc = umem_class_init(uma, &tins->ti_umm);
```
___
*[`dumps/dtx_update_abort.c` line 486 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2T6WZ9fkUSDzkkpCR:-Nh2T6WZ9fkUSDzkkpCS:bnnt8ig) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L486)):*
> ```C
>                                                                                 case UMEM_CLASS_PMEM:
>                                                                                         root_oid = pmemobj_root(pop, 0);
>                                                                                         root = pmemobj_direct(root_oid);
> ```

By writing just `/* umm->umm_id == UMEM_CLASS_PMEM */` you can flatten out the dump.



_Suggestion:_
```C
                                                                                /* umm->umm_id == UMEM_CLASS_PMEM */
                                                                                root_oid = pmemobj_root(pop, 0);
                                                                                root = pmemobj_direct(root_oid);
                                                                                umm->umm_pool_uuid_lo = root_oid.pool_uuid_lo;
                                                                                umm->umm_base = (uint64_t)root - root_oid.off;
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/daos/18)* status: all files reviewed, 19 unresolved discussions (waiting on @osalyk)

___
*[`dumps/dtx_update_abort.c` line 371 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh6HyhA3QR-4bBDXoz6:-Nh6HyhA3QR-4bBDXoz7:b-gsuxqr) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L371)):*
> ```C
> 			 * struct vos_io_context *ioc
> 			 */
>                         rc = key_tree_prepare(obj, obj->obj_toh, VOS_BTR_DKEY, dkey, SUBTR_CREATE, DAOS_INTENT_UPDATE, &krec, &ak_toh, ioc->ic_ts_set);
> ```

Whatever it means. :sweat_smile: 



_Suggestion:_
```C
/* Load the subtree roots embedded in the parent tree record. */
rc = key_tree_prepare(obj, obj->obj_toh, VOS_BTR_DKEY, dkey, SUBTR_CREATE, DAOS_INTENT_UPDATE, &krec, &ak_toh, ioc->ic_ts_set);
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/daos/18)* status: all files reviewed, 20 unresolved discussions (waiting on @osalyk)

___
*[`dumps/dtx_update_abort.c` line 371 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh6ULVgDO-hB56ZiPJm:-Nh6ULVgDO-hB56ZiPJn:b-vc4cwb) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L371)):*
> ```C
> 			 * struct vos_io_context *ioc
> 			 */
>                         rc = key_tree_prepare(obj, obj->obj_toh, VOS_BTR_DKEY, dkey, SUBTR_CREATE, DAOS_INTENT_UPDATE, &krec, &ak_toh, ioc->ic_ts_set);
> ```

I just found a very interesting piece of information. I believe it is worth putting it in as well.



_Code snippet:_
```C
/* Data structure which carries the value buffers, checksums and memory IDs to the multi-nested btree. */
struct vos_rec_bundle rbund;
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/daos/18)* status: all files reviewed, 21 unresolved discussions (waiting on @osalyk)

___
*[`dumps/dtx_update_abort.c` line 371 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh6VXn_7gtijVI-qis1:-Nh6VXn_7gtijVI-qis2:b-w7spwp) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L371)):*
> ```C
> 			 * struct vos_io_context *ioc
> 			 */
>                         rc = key_tree_prepare(obj, obj->obj_toh, VOS_BTR_DKEY, dkey, SUBTR_CREATE, DAOS_INTENT_UPDATE, &krec, &ak_toh, ioc->ic_ts_set);
> ```

:astonished: 



_Code snippet:_
```C
/* Persisted VOS (d/a)key record, it is referenced by btr_record::rec_off of btree VOS_BTR_DKEY/VOS_BTR_AKEY. */
struct vos_krec_df *krec = NULL;
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/daos/18)* status: 0 of 1 files reviewed, 21 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/janekmi/daos/18#-Nh2A42jDuqk5dUoevwz:-NhB7dL8BsXZGKjwXYdf:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Mixing tabs and spaces may cause problems in this case. Can you please replace tabs with spaces?
</blockquote></details>

Done.

___
___
*[`dumps/dtx_update_abort.c` line 370 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh1wGWIBgSGmTFFvTX-:-NhB864b2iiR9URiEwc3:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L370)):*
> ```C
> 			 * daos_handle_t ak_toh
> 			 * struct vos_io_context *ioc
> 			 */
> ```

Done.
___
*[`dumps/dtx_update_abort.c` line 371 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh29Ikp-q8N8xhqjMx6:-NhB8W_245hXKbTFVxto:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L371)):*
> ```C
> 			 * struct vos_io_context *ioc
> 			 */
>                         rc = key_tree_prepare(obj, obj->obj_toh, VOS_BTR_DKEY, dkey, SUBTR_CREATE, DAOS_INTENT_UPDATE, &krec, &ak_toh, ioc->ic_ts_set);
> ```

Done.
___
*[`dumps/dtx_update_abort.c` line 371 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh29RGl3Mg_mnQu5tYj:-NhB95FkAZs17abjxi1o:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L371)):*
> ```C
> 			 * struct vos_io_context *ioc
> 			 */
>                         rc = key_tree_prepare(obj, obj->obj_toh, VOS_BTR_DKEY, dkey, SUBTR_CREATE, DAOS_INTENT_UPDATE, &krec, &ak_toh, ioc->ic_ts_set);
> ```

Done.
___
*[`dumps/dtx_update_abort.c` line 371 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh6HyhA3QR-4bBDXoz6:-NhB9BBrAnFVyXUXrM-m:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L371)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Whatever it means. :sweat_smile:
</blockquote></details>

Done.
___
*[`dumps/dtx_update_abort.c` line 371 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh6ULVgDO-hB56ZiPJm:-NhB9O4fBUIfkZveYeCr:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L371)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I just found a very interesting piece of information. I believe it is worth putting it in as well.
</blockquote></details>

Done.
___
*[`dumps/dtx_update_abort.c` line 371 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh6VXn_7gtijVI-qis1:-NhB9qpjBJtUheq_eVE4:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L371)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:astonished:
</blockquote></details>

Done.
___
*[`dumps/dtx_update_abort.c` line 391 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh29dhK83HlQ5Q5llr3:-NhBA3Es5EqSC1F3fHDE:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L391)):*
> ```C
> 				*   there.
> 				*/
>                                 rc = dbtree_fetch(toh, BTR_PROBE_EQ, intent, key, NULL, &riov);
> ```

Done.
___
*[`dumps/dtx_update_abort.c` line 407 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh29nYT7ZLMK09sQv6y:-NhBAQaxB8hjqCuo3RWS:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L407)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can omit this piece.
</blockquote></details>

Done.
___
*[`dumps/dtx_update_abort.c` line 410 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh29zR59Ln2hWF6zz-d:-NhBAZHk79NIwl8PIRgI:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L410)):*
> ```C
>                                 /* rc == 0 */
> 				krec = rbund.rb_krec;
> 				ilog = &krec->kr_ilog;
> ```

Done.
___
*[`dumps/dtx_update_abort.c` line 415 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2AKpv9FGZ_2SfJblE:-NhBAiqg9u1KRFCTi_5y:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L415)):*
> ```C
>                                 vos_ilog_ts_ignore(vos_obj2umm(obj), &krec->kr_ilog);
>                                         /* !DAOS_ON_VALGRIND */
>                                 tmprc = vos_ilog_ts_add(ts_set, ilog, key->iov_buf, (int)key->iov_len);
> ```

Done.
___
*[`dumps/dtx_update_abort.c` line 418 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2ARnBB19ZZhZ9Aq7C:-NhBAxuU3pWRz93AdbqJ:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L418)):*
> ```C
>                                         /* vos_ts_in_tx(ts_set) == true */
>                                         /* ilog != NULL */
>                                         idx = ilog_ts_idx_get(ilog);
> ```

Done.
___
*[`dumps/dtx_update_abort.c` line 420 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2AWymDh0bT2FIrynq:-NhBB7F-CjBodr0ELlgj:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L420)):*
> ```C
>                                         idx = ilog_ts_idx_get(ilog);
>                                         vos_ts_set_add(ts_set, idx, record, rec_size);
>                                         	hash = vos_hash_get(rec, rec_size, false);
> ```

Done.
___
*[`dumps/dtx_update_abort.c` line 433 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2Ac4HE_SVMoTRMISo:-NhBBNoP5PJwY52dz7Tk:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L433)):*
> ```C
> 						 *		allocated or we detected a duplicate akey.
> 						*/
> 						entry = vos_ts_alloc(ts_set, idx, hash);
> ```

Done.
___
*[`dumps/dtx_update_abort.c` line 440 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2AmOy36Cwaap6xrtz:-NhBCAxx763g7jrmdOh_:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L440)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sorry for mixing tabs and spaces. I assumed it would be easier to follow this way.
</blockquote></details>

Done.
___
*[`dumps/dtx_update_abort.c` line 442 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2BBTn-1DPC8vQ7Rat:-NhBC_Wz9wNrJ3iT2tcE:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L442)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I would like to know the value of the `created` variable at this point. Can you please verify and add an appropriate line?
</blockquote></details>

Done.
___
*[`dumps/dtx_update_abort.c` line 443 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2BW7J9dwEA4vHfaX_:-NhBCv0kAp3ZNUSccdcu:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L443)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Missing definitions.
</blockquote></details>

Done.
___
*[`dumps/dtx_update_abort.c` line 455 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2BhUi0E4HtfvunVyn:-NhBDE6N4AAlLYSuyfSn:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L455)):*
> ```C
> 					 * \param toh		[OUT]	Returned tree open handle.
> 					 */
>                                         dbtree_open_inplace_ex(&krec->kr_btr, uma, coh, pool, sub_toh);
> ```

Done.
___
*[`dumps/dtx_update_abort.c` line 469 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2BxuO5bElUskfFdZS:-NhBDxqdAx649TyvFiq2:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L469)):*
> ```C
> 						* \param tcxp		Returned context.
> 						*/
>                                                 rc = btr_context_create(BTR_ROOT_NULL, root, -1, -1, -1, uma, coh, priv, &tcx);
> ```

Done.
___
*[`dumps/dtx_update_abort.c` line 480 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2SwtQBePIch_a1XjP:-NhBE7C11iolaKJPJufr:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L480)):*
> ```C
> 								 * \param umm [OUT]	The instantiated memory class.
> 								 */
> 								rc = umem_class_init(uma, &tins->ti_umm);
> ```

Done.
___
*[`dumps/dtx_update_abort.c` line 486 at r1](https://reviewable.io/reviews/janekmi/daos/18#-Nh2T6WZ9fkUSDzkkpCR:-NhBEQmT1y8JUYW24k9v:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/685b368e1b1f36e95c128628e25b4c7c2957a5bf/dumps/dtx_update_abort.c#L486)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

By writing just `/* umm->umm_id == UMEM_CLASS_PMEM */` you can flatten out the dump.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/janekmi/daos/18#-:-NhCUhbk6HDML6eYTmtT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
