### PR TITLE
vos: local_transaction test with pre-step

### PR DESCRIPTION
**Pull request by grom72**
### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

- - -
This change is [Reviewable](https://reviewable.io/reviews/janekmi/daos/1)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/janekmi/daos/1)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[`src/vos/tests/vts_pm.c` line 2764 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgNs-JD1AD7ItvD46_o:-NgNs-JD1AD7ItvD46_p:b1916am) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2764)):*
> ```C
> 
> 		d_iov_set(&fetch_sgl.sg_iovs[0], (void *)buf, sizeof(buf));
> 		iod.iod_size = sizeof(buf);
> ```

I think in the case of `vos_obj_fetch()` this value is actually an output not an input. Hence, its value should be irrelevant.

You can see it here: 

```
#0  0x00007ffff7acff97 in akey_fetch (ioc=ioc@entry=0x55555922bdb0, ak_toh=...) at src/vos/vos_io.c:1262
#1  0x00007ffff7ad10b7 in dkey_fetch (ioc=0x55555922bdb0, dkey=dkey@entry=0x7fffffffc590) at src/vos/vos_io.c:1413
#2  0x00007ffff7ad64d8 in vos_fetch_begin (coh=..., oid=..., epoch=<optimized out>, dkey=0x7fffffffc590, iod_nr=iod_nr@entry=1, iods=0x7fffffffc520, vos_flags=<optimized out>, shadows=0x0, ioh=0x7fffff
ffc400, dth=0x0) at src/vos/vos_io.c:1513
#3  0x00007ffff7adeffd in vos_obj_fetch_ex (coh=..., oid=..., epoch=<optimized out>, flags=<optimized out>, dkey=<optimized out>, iod_nr=1, iods=<optimized out>, sgls=0x7fffffffc4d0, dth=0x0) at src/vo
s/vos_io.c:2838
#4  0x00007ffff7adf499 in vos_obj_fetch (coh=..., oid=..., epoch=<optimized out>, flags=<optimized out>, dkey=<optimized out>, iod_nr=<optimized out>, iods=<optimized out>, sgls=0x7fffffffc4d0) at src/
vos/vos_io.c:2876
```

Where `&iod_iod_size` is passed as an output argument to read the record size (rsize) [here](https://github.com/grom72/daos/blob/master/src/vos/vos_io.c#L836).

So, if anything, we should set it to something ridiculous like `SIZE_MAX`.
___
*[`src/vos/tests/vts_pm.c` line 2781 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgNzllvC1T0ETzSEpK3:-NgNzllvC1T0ETzSEpK4:undefined) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2781)):*
> ```C
> 			assert_int_equal(fetch_sgl.sg_iovs[0].iov_len,(int)strlen(first));
> 			assert_memory_equal(buf, buf2, fetch_sgl.sg_iovs[0].iov_len);
> 		}
> ```





_Suggestion:_
```C
		if (i == 0) {
			/** On abort, the value is not meant to be found hence the output size == 0 */
			assert_int_equal(iod.iod_size, 0);
		} else {
			/** On commit, the value is expected to be available */
			assert_int_equal(iod.iod_size, (int)strlen(first));
			assert_int_equal(fetch_sgl.sg_iovs[0].iov_len, (int)strlen(first));
			assert_memory_equal(buf, buf2, fetch_sgl.sg_iovs[0].iov_len);
		}
```
___
*[`src/vos/tests/vts_pm.c` line 2790 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO-yt_5yaGTqscGRHq:-NgO-yt_5yaGTqscGRHr:undefined) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2790)):*
> ```C
> 		    vos_obj_fetch(arg->ctx.tc_co_hdl, oid, epoch, 0, &dkey[1], 1, &iod, &fetch_sgl);
> 		assert_rc_equal(rc, 0);
> 		assert_rc_equal(iod.iod_size,0);
> ```





_Suggestion:_
```C
/** The punched key is not meant to be found hence the output size == 0 */
assert_rc_equal(iod.iod_size, 0);
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/daos/1)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @grom72)

___
*[`src/vos/tests/vts_pm.c` line 2692 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO0fyiANkYZgrlsrzY:-NgO0fyiANkYZgrlsrzZ:b-yihr58) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2692)):*
> ```C
> 	{
> 		rc = vos_obj_update(arg->ctx.tc_co_hdl, oid, epoch++, 0, 0, &dkey[2], 1, &iod,
> 				       NULL, &sgl);
> ```

Maybe having a dedicated value for a neighbouring value would make sense?
Just in case, we run into reading a value but not the one we meant to.
___
*[`src/vos/tests/vts_pm.c` line 2694 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO1RBdE0GyKYnKu6D4:-NgO1RBdE0GyKYnKu6D5:b-okasak) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2694)):*
> ```C
> 				       NULL, &sgl);
> 		assert_rc_equal(rc, 0);
> 		/* prepare fetch buffer with random data */
> ```

It is not exactly random.



_Suggestion:_
```C
/* prepare fetch buffer with distinct initial content */
```
___
*[`src/vos/tests/vts_pm.c` line 2696 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO1_kq4JVMOZu0BOO0:-NgO1_kq4JVMOZu0BOO1:b-y5vset) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2696)):*
> ```C
> 		/* prepare fetch buffer with random data */
> 		d_iov_set(&fetch_sgl.sg_iovs[0], (void *)buf, sizeof(buf));
> 		iod.iod_size = sizeof(buf);
> ```

Please see the comment below.
___
*[`src/vos/tests/vts_pm.c` line 2716 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO1p-D4njVUnDcbCuf:-NgO1p-D4njVUnDcbCug:b3kqx) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2716)):*
> ```C
> 		assert_memory_equal(buf, buf2, (int)strlen(first));
> 
> 		/* prepare fetch buffer with random data */
> ```

.
___
*[`src/vos/tests/vts_pm.c` line 2731 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO1yLY6zfG5q9_Zn85:-NgO1yLY6zfG5q9_Zn86:b-pau1cj) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2731)):*
> ```C
> 		assert_int_equal(iod.iod_size,0);
> 		assert_int_equal(fetch_sgl.sg_iovs[0].iov_len,0);
> 		assert_memory_equal(buf, buf2, sizeof(buf));
> ```

I think we should assume the output contents in undefined since VOS reported its size == 0 aka non-existent.



_Suggestion:_
```C
		rc =
		    vos_obj_fetch(arg->ctx.tc_co_hdl, oid, epoch, 0, &dkey[3], 1, &iod, &fetch_sgl);
		assert_rc_equal(rc, 0);
		printf("size=" DF_U64 "\n", iod.iod_size);
		printf("dkey[3] buf = %.*s\n", (int)strlen(first), buf);
		fflush(stdout);
		assert_int_equal(iod.iod_size, 0);
		assert_int_equal(fetch_sgl.sg_iovs[0].iov_len, 0);
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/daos/1)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[`src/vos/tests/vts_pm.c` line 2692 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO0fyiANkYZgrlsrzY:-NgOHq3D6caGXQfgtvdg:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2692)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Maybe having a dedicated value for a neighbouring value would make sense?
Just in case, we run into reading a value but not the one we meant to.
</blockquote></details>

Done.
___
*[`src/vos/tests/vts_pm.c` line 2694 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO1RBdE0GyKYnKu6D4:-NgOHrVJ4VFTtp2vlR9Q:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2694)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not exactly random.
</blockquote></details>

Done.
___
*[`src/vos/tests/vts_pm.c` line 2696 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO1_kq4JVMOZu0BOO0:-NgOHt4h-zaFhT3orrhn:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2696)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please see the comment below.
</blockquote></details>

Done.
___
*[`src/vos/tests/vts_pm.c` line 2716 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO1p-D4njVUnDcbCuf:-NgOI2LHDsQeeikzNZL7:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2716)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`src/vos/tests/vts_pm.c` line 2731 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO1yLY6zfG5q9_Zn85:-NgO6mwX-K5bAD6SXib-:b-tbvyax) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2731)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we should assume the output contents in undefined since VOS reported its size == 0 aka non-existent.
</blockquote></details>

I understand that the original test implementation assumes that SGL buffers should not be affected in case no data is to be read.
___
*[`src/vos/tests/vts_pm.c` line 2764 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgNs-JD1AD7ItvD46_o:-NgOIHrpBy0HaB3nns9K:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2764)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think in the case of `vos_obj_fetch()` this value is actually an output not an input. Hence, its value should be irrelevant.

You can see it here: 

```
#0  0x00007ffff7acff97 in akey_fetch (ioc=ioc@entry=0x55555922bdb0, ak_toh=...) at src/vos/vos_io.c:1262
#1  0x00007ffff7ad10b7 in dkey_fetch (ioc=0x55555922bdb0, dkey=dkey@entry=0x7fffffffc590) at src/vos/vos_io.c:1413
#2  0x00007ffff7ad64d8 in vos_fetch_begin (coh=..., oid=..., epoch=<optimized out>, dkey=0x7fffffffc590, iod_nr=iod_nr@entry=1, iods=0x7fffffffc520, vos_flags=<optimized out>, shadows=0x0, ioh=0x7fffff
ffc400, dth=0x0) at src/vos/vos_io.c:1513
#3  0x00007ffff7adeffd in vos_obj_fetch_ex (coh=..., oid=..., epoch=<optimized out>, flags=<optimized out>, dkey=<optimized out>, iod_nr=1, iods=<optimized out>, sgls=0x7fffffffc4d0, dth=0x0) at src/vo
s/vos_io.c:2838
#4  0x00007ffff7adf499 in vos_obj_fetch (coh=..., oid=..., epoch=<optimized out>, flags=<optimized out>, dkey=<optimized out>, iod_nr=<optimized out>, iods=<optimized out>, sgls=0x7fffffffc4d0) at src/
vos/vos_io.c:2876
```

Where `&iod_iod_size` is passed as an output argument to read the record size (rsize) [here](https://github.com/grom72/daos/blob/master/src/vos/vos_io.c#L836).

So, if anything, we should set it to something ridiculous like `SIZE_MAX`.
</blockquote></details>

Done.
___
*[`src/vos/tests/vts_pm.c` line 2781 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgNzllvC1T0ETzSEpK3:-NgOJi_80CxUv5isL0QV:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2781)):*
> ```C
> 			assert_int_equal(fetch_sgl.sg_iovs[0].iov_len,(int)strlen(first));
> 			assert_memory_equal(buf, buf2, fetch_sgl.sg_iovs[0].iov_len);
> 		}
> ```

Done.
___
*[`src/vos/tests/vts_pm.c` line 2790 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO-yt_5yaGTqscGRHq:-NgOJjlM1vqbX6JQtUeh:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2790)):*
> ```C
> 		    vos_obj_fetch(arg->ctx.tc_co_hdl, oid, epoch, 0, &dkey[1], 1, &iod, &fetch_sgl);
> 		assert_rc_equal(rc, 0);
> 		assert_rc_equal(iod.iod_size,0);
> ```

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/janekmi/daos/1)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[`src/vos/tests/vts_pm.c` line 2696 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO1_kq4JVMOZu0BOO0:-NgONi8gC_BdSnCOJaiu:bhopwig) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2696)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`iod.iod_size = UINT64_MAX;`
___
*[`src/vos/tests/vts_pm.c` line 2716 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO1p-D4njVUnDcbCuf:-NgOMdpDCX4bHCoaVsM3:bniihrl) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2716)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant `/* prepare fetch buffer with distinct initial content */`. I see no randomness here. :wink: 
___
*[`src/vos/tests/vts_pm.c` line 2692 at r2](https://reviewable.io/reviews/janekmi/daos/1#-NgOLxuyDyu6SNz2k_9_:-NgOLxuyDyu6SNz2k_9a:undefined) ([raw file](https://github.com/janekmi/daos/blob/6a83a547e08805a17aaf0e28d7385097a0d8530b/src/vos/tests/vts_pm.c#L2692)):*
> ```C
> 		const char *pre_test_data = "Aloha";
> 
> 		iod.iod_size  = strlen(pre_test_data);
> ```





_Suggestion:_
```C
iod.iod_size = strlen(pre_test_data);
d_iov_set(&sgl.sg_iovs[0], (void *)pre_test_data, iod.iod_size);
```

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/janekmi/daos/1)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/janekmi/daos/1)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[`src/vos/tests/vts_pm.c` line 2716 at r1](https://reviewable.io/reviews/janekmi/daos/1#-NgO1p-D4njVUnDcbCuf:-NgOgq99CKieQNKNumRa:b-896fix) ([raw file](https://github.com/janekmi/daos/blob/2103c0e0f4d901a07811e25ec81cdcccdf134351/src/vos/tests/vts_pm.c#L2716)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I meant `/* prepare fetch buffer with distinct initial content */`. I see no randomness here. :wink:
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/janekmi/daos/1)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/janekmi/daos/1#-:-NgOhGoCA3Jobpv6O57L:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
